
name: Contract Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node LTS
      uses: actions/setup-node@v2
      with:
        node-version: "lts/*"
    
    - name: Run Era Test Node
      uses: dutterbutter/era-test-node-action@latest

    - name: Install dependencies with Yarn
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn tests
