
name: E2E Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run Era Test Node
      uses: dutterbutter/era-test-node-action@latest
    - name: Run E2E tests
      run: |
        chmod +x test/e2e/test.sh
        ./test/e2e/test.sh
